const fs = require('fs');

const ptPath = 'src/i18n/locales/pt.json';
const pt = JSON.parse(fs.readFileSync(ptPath, 'utf8'));

pt.social_page_b2b.projects.women.desc = "Integrando nossas metodologias Biostretch e Be the Dance, oferecemos um espaço focado em mulheres. Ao unir movimento consciente e expressão artística, promovemos a saúde preventiva, o bem-estar pessoal e o autoconhecimento, criando um ponto de encontro seguro e vital contra o isolamento social.";
pt.btd_kvinne.body.p1 = "Dance2Dance Kvinne propõe um espaço seguro onde o corpo deixa de ser objeto de regulação, controle e disciplina para se tornar uma bússola de autoconhecimento. Ao acolher mulheres em um ambiente livre de expectativas externas e julgamentos, criamos uma transição suave entre a agitação do cotidiano e o reencontro com aquilo que existe de mais genuíno em cada uma: sua própria essência.\n\nQuando começamos a questionar as normas que determinam o que deve ser um corpo “saudável”, “produtivo”, “belo” ou “comportado”, abrimos espaço para uma escuta mais profunda das necessidades reais do corpo. Reconhecer a fome, o cansaço, a dor, o prazer, o desejo e os próprios limites é também recuperar a capacidade de decidir sobre o próprio corpo e resistir aos padrões que procuram regulá-lo e padronizá-lo.";
pt.btd_kvinne.body.p2 = "A dança torna-se, nesse processo, uma poderosa ferramenta de reconexão consigo mesma e com as outras. Por meio do movimento, da presença e da escuta corporal, criamos possibilidades para desenvolver resiliência, autonomia e empoderamento, não para transformar o corpo em algo a ser aperfeiçoado, mas para habitá-lo com mais liberdade, consciência e confiança.\n\nO projeto integra a escuta sensível do Biostretch à celebração libertadora do Be The Dance. Por meio da respiração consciente, da sensibilização e da exploração do ritmo próprio, cada participante é convidada a desacelerar, reconhecer suas necessidades e aprofundar sua presença no corpo. Com a continuidade da prática, tensões acumuladas podem ser liberadas, fortalecendo a autonomia física e emocional e ampliando a confiança na própria capacidade de sentir, escolher e agir.";
pt.btd_kvinne.body.p3 = "Ao colocar o cuidado de si como uma dimensão fundamental da vida das mulheres, contribuímos também para a construção de comunidades mais fortes e conectadas. O projeto oferece bolsas integrais para moradoras de Tøyen e Grønland, mantendo-se, ao mesmo tempo, aberto a mulheres de toda a cidade. Essa diversidade de experiências e trajetórias amplia a rede de apoio mútuo e favorece a criação de vínculos que ultrapassam o espaço da prática.\n\nDessa forma, o cuidado individual torna-se também uma força coletiva: as participantes levam consigo novas ferramentas de autocuidado, consciência corporal e autonomia, tornando-se potenciais agentes multiplicadoras de bem-estar e saúde integrativa em suas famílias, redes e comunidades.";
pt.btd_kvinne.impact_section.items[0].desc = "A integração de práticas somáticas contribui para a redução do estresse crônico e para a recuperação da autonomia sobre o próprio corpo. Ao romper com padrões de controle e aprender a reconhecer suas próprias necessidades, as mulheres fortalecem a resiliência, a clareza mental e a capacidade de tomar decisões a partir de uma relação mais livre e consciente consigo mesmas.";
pt.btd_kvinne.impact_section.items[2].desc = "O bem-estar feminino é o alicerce da saúde familiar. Uma mulher fortalecida irradia essa estabilidade para seus filhos e seu entorno, gerando um ciclo positivo de impacto.";
pt.btd_kvinne.mentorText = "Um ambiente seguro onde cada mulher é estimulada a descobrir seu próprio movimento e recuperar o prazer de habitar o próprio corpo.";

fs.writeFileSync(ptPath, JSON.stringify(pt, null, 2), 'utf8');

const enPath = 'src/i18n/locales/en.json';
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

en.social_page_b2b.projects.women.desc = "Integrating our Biostretch and Be the Dance methodologies, we offer a space focused on women. By uniting conscious movement and artistic expression, we promote preventive health, personal well-being, and self-discovery, creating a safe and vital meeting point against social isolation.";
en.btd_kvinne.body.p1 = "Dance2Dance Kvinne offers a safe space where the body ceases to be an object of regulation, control, and discipline to become a compass for self-discovery. By welcoming women into an environment free of external expectations and judgment, we create a smooth transition between the daily hustle and the reconnection with what is most genuine in each of them: their own essence.\n\nWhen we begin to question the norms that dictate what a “healthy,” “productive,” “beautiful,” or “well-behaved” body should be, we make room for a deeper listening to the body’s real needs. Recognizing hunger, fatigue, pain, pleasure, desire, and our own limits is also reclaiming the ability to decide about our own body and resisting the standards that seek to regulate and standardize it.";
en.btd_kvinne.body.p2 = "In this process, dance becomes a powerful tool for reconnection with oneself and with others. Through movement, presence, and bodily listening, we create possibilities to develop resilience, autonomy, and empowerment—not to transform the body into something to be perfected, but to inhabit it with greater freedom, awareness, and confidence.\n\nThe project integrates the sensitive listening of Biostretch with the liberating celebration of Be The Dance. Through conscious breathing, sensitization, and the exploration of their own rhythm, each participant is invited to slow down, recognize their needs, and deepen their presence in the body. With continued practice, accumulated tensions can be released, strengthening physical and emotional autonomy and expanding confidence in one's own ability to feel, choose, and act.";
en.btd_kvinne.body.p3 = "By placing self-care as a fundamental dimension of women’s lives, we also contribute to building stronger, more connected communities. The project offers full scholarships for residents of Tøyen and Grønland, while remaining open to women from all over the city. This diversity of experiences and backgrounds broadens the mutual support network and fosters the creation of bonds that extend beyond the practice space.\n\nIn this way, individual care also becomes a collective force: participants carry with them new tools for self-care, body awareness, and autonomy, becoming potential multiplier agents of well-being and integrative health in their families, networks, and communities.";
en.btd_kvinne.impact_section.items[0].desc = "The integration of somatic practices contributes to the reduction of chronic stress and the recovery of autonomy over one's own body. By breaking with patterns of control and learning to recognize their own needs, women strengthen resilience, mental clarity, and the ability to make decisions from a freer, more conscious relationship with themselves.";
en.btd_kvinne.impact_section.items[2].desc = "Women's well-being is the foundation of family health. A strengthened woman radiates this stability to her children and surroundings, generating a positive cycle of impact.";
en.btd_kvinne.mentorText = "A safe environment where each woman is encouraged to discover her own movement and reclaim the joy of inhabiting her own body.";

fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');

const noPath = 'src/i18n/locales/no.json';
const no = JSON.parse(fs.readFileSync(noPath, 'utf8'));

no.social_page_b2b.projects.women.desc = "Ved å integrere våre Biostretch- og Be the Dance-metodikker, tilbyr vi et rom med fokus på kvinner. Gjennom å forene bevisst bevegelse og kunstnerisk uttrykk, fremmer vi forebyggende helse, personlig velvære og selvinnsikt, og skaper en trygg og livsviktig møteplass mot sosial isolasjon.";
no.btd_kvinne.body.p1 = "Dance2Dance Kvinne tilbyr et trygt rom der kroppen slutter å være et objekt for regulering, kontroll og disiplin, og i stedet blir et kompass for selvinnsikt. Ved å ta imot kvinner i et miljø fritt for ytre forventninger og dømming, skaper vi en myk overgang mellom hverdagens kjas og gjenoppdagelsen av det som er mest genuint i hver enkelt: deres egen essens.\n\nNår vi begynner å stille spørsmål ved normene som dikterer hva en «sunn», «produktiv», «vakker» eller «veloppdragen» kropp skal være, gir vi rom for å lytte dypere til kroppens reelle behov. Å anerkjenne sult, tretthet, smerte, nytelse, begjær og egne grenser, handler også om å ta tilbake evnen til å bestemme over egen kropp og yte motstand mot standardene som forsøker å regulere og standardisere den.";
no.btd_kvinne.body.p2 = "I denne prosessen blir dansen et kraftfullt verktøy for å finne tilbake til seg selv og andre. Gjennom bevegelse, tilstedeværelse og kroppslig lytting skaper vi muligheter for å utvikle robusthet, autonomi og empowerment – ikke for å forvandle kroppen til noe som skal perfeksjoneres, men for å bebo den med større frihet, bevissthet og tillit.\n\nProsjektet integrerer den sensitive lyttingen fra Biostretch med den frigjørende feiringen av Be The Dance. Gjennom bevisst pust, bevisstgjøring og utforskning av egen rytme, inviteres hver deltaker til å bremse ned, anerkjenne egne behov og utdype tilstedeværelsen i kroppen. Ved kontinuerlig praksis kan oppbygde spenninger frigjøres, noe som styrker fysisk og emosjonell autonomi og øker tilliten til egen evne til å føle, velge og handle.";
no.btd_kvinne.body.p3 = "Ved å sette egenomsorg som en grunnleggende dimensjon i kvinners liv, bidrar vi også til å bygge sterkere og mer sammenknyttede lokalsamfunn. Prosjektet tilbyr fulle stipender for innbyggere i Tøyen og Grønland, samtidig som det er åpent for kvinner fra hele byen. Dette mangfoldet av erfaringer og bakgrunner utvider det gjensidige støttenettverket og fremmer bånd som strekker seg langt utover selve praksisrommet.\n\nPå denne måten blir den individuelle omsorgen også en kollektiv kraft: deltakerne tar med seg nye verktøy for egenomsorg, kroppsbevissthet og autonomi, og blir potensielle multiplikatorer for velvære og integrativ helse i sine familier, nettverk og lokalsamfunn.";
no.btd_kvinne.impact_section.items[0].desc = "Integreringen av somatisk praksis bidrar til reduksjon av kronisk stress og gjenvinning av autonomi over egen kropp. Ved å bryte med kontrollmønstre og lære å anerkjenne egne behov, styrker kvinnene sin robusthet, mentale klarhet og evne til å ta beslutninger ut fra en friere og mer bevisst relasjon til seg selv.";
no.btd_kvinne.impact_section.items[2].desc = "Kvinners velvære er grunnmuren i familiens helse. En styrket kvinne utstråler denne stabiliteten til sine barn og omgivelser, og skaper en positiv sirkel av innvirkning.";
no.btd_kvinne.mentorText = "Et trygt miljø der hver kvinne oppmuntres til å oppdage sin egen bevegelse og gjenvinne gleden ved å bebo sin egen kropp.";

fs.writeFileSync(noPath, JSON.stringify(no, null, 2), 'utf8');

console.log('JSON keys updated with new deep content.');
